// TurboQuant tq3_0 K-cache with f16 V-cache flash attention
#include "../fattn-vec.cuh"
DECL_FATTN_VEC_CASE( 64, GGML_TYPE_TQ3_0, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_TQ3_0, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_TQ3_0, GGML_TYPE_F16);
